import type { Item } from 'vue3-easy-data-table';

import type { TaskType } from '@/types/task';

export const SUMMARY = [
  {
    title: 'Working Day(s)',
    subtitle: `2 Hari`,
  },
  {
    title: 'Working Hour(s)',
    subtitle: `13 hr 14 min`,
  },
  {
    title: 'Exceptional Attendance',
    subtitle: `0 Hari`,
  },
  {
    title: 'Leave Taken',
    subtitle: `0 Hari`,
  },
  {
    title: 'Overtime',
    subtitle: `00 hr 00 min`,
  },
  {
    title: 'Claim',
    subtitle: `IDR 0`,
  },
];

export const TASK_DUE_SOON: TaskType[] = [
  {
    status: 'unscheduled',
    progress_status: 'on-progress',
    type: 'UI/UX Design',
    title: '[Wms][Web][Task] Create Goals Design',
    subtitle: `UI/UX Designer`,
    total_task: 44,
    total_comment: 1,
    level: 'Medium',
    date_scheduled: '06 Aug 2021',
    date_created: '10 Mar 21 at 13:30',
  },
  {
    status: 'unscheduled',
    progress_status: 'on-progress',
    type: 'Frontend',
    title: '[Wms][Web][Task] Integeration API',
    subtitle: `Front End Dev`,
    total_task: 102,
    total_comment: 5,
    level: 'Hard',
    date_scheduled: '22 Jan 2022',
    date_created: '10 Mar 21 at 13:30',
  },
  {
    status: 'unscheduled',
    progress_status: 'on-progress',
    type: 'Backend',
    title: '[Wms][Web][Task] Export Database',
    subtitle: `Backend End Dev`,
    total_task: 17,
    total_comment: 3,
    level: 'Easy',
    date_scheduled: '11 Des 2023',
    date_created: '10 Mar 21 at 13:30',
  },
];

export const MONTH_NAMES = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export const TABLE_DATA: Item[] = [
  {
    leaveCode: 'LV-PTES-PT-CV10435-01-23-001',
    requestOn: 'Mon, 02 Jan 2023',
    leaveType: 'Annual Leave',
    startDate: 'Tue, 03 Jan 2023',
    endDate: 'Tue, 03 Jan 2023',
    duration: '1 Day(s)',
    day: 'Full Day',
    leave_category: 'Normal Leave',
    status: 'approve',
    reason: 'Family Event',
  },
  {
    leaveCode: 'LV-PTES-PT-CV10435-01-23-001',
    requestOn: 'Mon, 12 Jan 2023',
    leaveType: 'Sick Leave',
    startDate: 'Tue, 11 Jan 2023',
    endDate: 'Tue, 03 Jan 2023',
    duration: '2 Day(s)',
    day: 'Full Day',
    leave_category: 'Normal Leave',
    status: 'reject',
    reason: 'Family Event',
  },
  {
    leaveCode: 'LV-PTES-PT-CV10435-01-23-001',
    requestOn: 'Mon, 22 Jan 2023',
    leaveType: 'Annual Leave',
    startDate: 'Tue, 21 Jan 2023',
    endDate: 'Tue, 03 Jan 2023',
    duration: '3 Day(s)',
    day: 'Half Day - Second Half',
    leave_category: 'Normal Leave',
    status: 'pending',
    reason: 'Family Event',
  },
  {
    leaveCode: 'LV-PTES-PT-CV10435-01-23-001',
    requestOn: 'Mon, 14 Jan 2023',
    leaveType: 'Sick Leave',
    startDate: 'Tue, 30 Jan 2023',
    endDate: 'Tue, 03 Jan 2023',
    duration: '0.5 Day(s)',
    day: 'Full Day',
    leave_category: 'Normal Leave',
    status: 'approve',
    reason: 'Family Event',
  },
  {
    leaveCode: 'LV-PTES-PT-CV10435-01-23-001',
    requestOn: 'Mon, 20 Jan 2023',
    leaveType: 'Annual Leave',
    startDate: 'Tue, 09 Jan 2023',
    endDate: 'Tue, 03 Jan 2023',
    duration: '1 Day(s)',
    day: 'Half Day - Second Half',
    leave_category: 'Normal Leave',
    status: 'approve',
    reason: 'Family Event',
  },
  {
    leaveCode: 'LV-PTES-PT-CV10435-01-23-001',
    requestOn: 'Mon, 12 Jan 2023',
    leaveType: 'Sick Leave',
    startDate: 'Tue, 01 Jan 2023',
    endDate: 'Tue, 03 Jan 2023',
    duration: '0.5 Day(s)',
    day: 'Full Day',
    leave_category: 'Normal Leave',
    status: 'reject',
    reason: 'Family Event',
  },
  {
    leaveCode: 'LV-PTES-PT-CV10435-01-23-001',
    requestOn: 'Mon, 08 Jan 2023',
    leaveType: 'Annual Leave',
    startDate: 'Tue, 14 Jan 2023',
    endDate: 'Tue, 03 Jan 2023',
    duration: '2 Day(s)',
    day: 'Half Day - First Half',
    leave_category: 'Normal Leave',
    status: 'pending',
    reason: 'Family Event',
  },
];
